# Generated by Django 5.1.3 on 2024-12-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('service', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('goal', models.TextField()),
            ],
        ),
    ]
